DROP TABLE IF EXISTS bonds;
DROP TABLE IF EXISTS issuers;
DROP TABLE IF EXISTS last_modified;
DROP TABLE IF EXISTS instrument_types;
DROP TABLE IF EXISTS markets;
DROP TABLE IF EXISTS bond_markets;
DROP TABLE IF EXISTS indexes;
DROP TABLE IF EXISTS bond_payment_dates;

DROP VIEW IF EXISTS bonds_view;
